apiVersion: v2
name: rabbitmq-wrapper
description: Wrapper for Bitnami RabbitMQ
type: application
version: 0.1.0

dependencies:
  - name: rabbitmq
    version: "16.0.14"
    repository: "https://charts.bitnami.com/bitnami"