apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-creds
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-init-secrets
  data:
  - secretKey: POSTGRESQL_PASSWORD
    remoteRef:
      key: postgresql
      property: admin_password
  - secretKey: AUTH_PASS
    remoteRef:
      key: postgresql
      property: auth_pass
  - secretKey: PRODUCT_PASS
    remoteRef:
      key: postgresql
      property: product_pass
  - secretKey: ORDER_PASS
    remoteRef:
      key: postgresql
      property: order_pass