apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-creds
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rabbitmq-credentials
  data:
  - secretKey: rabbitmq-password
    remoteRef:
      key: rabbitmq
      property: password
  - secretKey: rabbitmq-erlang-cookie
    remoteRef:
      key: rabbitmq
      property: erlang_cookie