apiVersion: v2
name: postgres-wrapper
description: Wrapper for Bitnami Postgres
type: application
version: 0.1.0

dependencies:
  - name: postgresql
    version: "18.2.4"
    repository: "https://charts.bitnami.com/bitnami"